# ModernZ v0.3.3 overrides only; unspecified options inherit upstream defaults.
language=en
icon_theme=fluent
icon_style=mixed

hidetimeout=2000
keeponpause=bottombar
fadein=no
osc_on_seek=no
osc_on_start=no

jump_buttons=yes
jump_amount=10
chapter_skip_buttons=no
playlist_button=yes
screenshot_button=yes
ontop_button=yes
loop_button=no
speed_button=no
info_button=yes
fullscreen_button=yes
download_button=no

seekbarfg_color=#FB8C00
seekbarbg_color=#94754F
seekbar_cache_color=#918F8E
hover_effect_color=#FB8C00
nibbles_style=triangle
persistent_progress=no
visibility=auto
